import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  translations: Record<string, Record<string, string>>;
}

const translations: Record<string, Record<string, string>> = {
  en: {
    // Header
    features: "Features",
    platform: "Platform",
    pricing: "Pricing",
    supportNav: "Support",
    login: "Log In",
    getStarted: "Get Started",
    
    // Hero
    powerYourEdge: "Power Your Edge",
    tradeSmarter: "Trade Smarter",
    winDaily: "Win Daily",
    heroDescription: "Welcome to EdgeTrade Pro, the U.S.-based trading platform built for serious day traders.",
    startTradingNow: "Start Trading Now",
    watchDemo: "Watch Demo",
    realtimeData: "Real-time Data",
    advancedCharts: "Advanced Charts",
    fastExecution: "Fast Execution",
    secProtected: "SEC Protected",
    
    // Features Section
    builtForProfessional: "Built for Professional Traders",
    featuresDescription: "Everything you need to execute your trading strategy with precision, speed, and confidence.",
    realtimeMarketData: "Real-time Market Data",
    realtimeMarketDataDesc: "Lightning-fast data feeds with Level II quotes and real-time streaming for all major exchanges.",
    advancedCharting: "Advanced Charting & Analytics",
    advancedChartingDesc: "Professional-grade charts with 100+ technical indicators, custom studies, and multi-timeframe analysis.",
    directAccessRouting: "Direct Access Routing",
    directAccessRoutingDesc: "Connect directly to market makers and ECNs for the fastest execution and best pricing available.",
    secRegistered: "SEC-Registered & SIPC-Protected",
    secRegisteredDesc: "Trade with confidence knowing your account is protected by SIPC insurance and SEC regulation.",
    subMillisecondExecution: "Sub-millisecond Execution",
    subMillisecondExecutionDesc: "Ultra-low latency order execution with co-located servers for maximum speed advantage.",
    competitivePricing: "Competitive Pricing",
    competitivePricingDesc: "Transparent, low-cost commission structure with no hidden fees or account minimums.",
    bankLevelSecurity: "Bank-Level Security",
    bankLevelSecurityDesc: "Multi-factor authentication, encryption, and cold storage protection for your funds.",
    advancedOrderTypes: "Advanced Order Types",
    advancedOrderTypesDesc: "Full suite of order types including bracket orders, trailing stops, and algorithmic strategies.",
    
    // Trust Indicators
    trustedBy: "Trusted by 50,000+ Active Traders",
    trustDescription: "Your security and success are our top priorities",
    secRegisteredTitle: "SEC Registered",
    secRegisteredText: "Fully regulated by the Securities and Exchange Commission",
    sipcProtected: "SIPC Protected",
    sipcProtectedText: "Your securities protected up to $500,000 by SIPC insurance",
    finraMember: "FINRA Member",
    finraMemberText: "Member of Financial Industry Regulatory Authority",
    awardWinning: "Award Winning",
    awardWinningText: "Best Trading Platform 2024 - Trading Magazine",
    sslEncryption: "256-bit SSL Encryption",
    tfaAuthentication: "2FA Authentication",
    coldStorage: "Cold Storage Protection",
    securityMonitoring: "24/7 Security Monitoring",
    
    // Call to Action
    readyToDominate: "Ready to Dominate the Markets?",
    ctaDescription: "Join thousands of successful day traders who trust EdgeTrade Pro for their daily trading operations.",
    openFreeAccount: "Open Free Account",
    platformDemo: "Platform Demo",
    minDeposit: "$250 minimum deposit required",
    freeRealtimeData: "Free real-time data for new accounts",
    customerSupport247: "24/7 customer support",
    
    // Sidebar
    overview: "Overview",
    exchange: "Exchange",
    withdraw: "Withdraw",
    transactions: "Transactions",
    walletAddress: "Wallet Address",
    vipTradingOffers: "VIP Trading Offers",
    supportInbox: "Support Inbox",
    kycVerification: "KYC Verification",
    settings: "Settings",
    
    // Dashboard
    welcomeBack: "Welcome back!",
    dashboard: "Dashboard",
    support: "Support",
    myWallets: "My Wallets",
    trading: "Trading",
    walletManagement: "Wallet Management",
    securityVerification: "Security & Verification",
    signOut: "Sign Out",
    demoAccount: "Demo Account",
    demoNotice: "You're in demo mode with $10,000 virtual balance. Create a free account to start real trading.",
    createFreeAccount: "Create Free Account",
    verifyKycNotice: "Please verify your KYC information before any transactional action.",
    verifyNow: "Verify Now",
    portfolioSummary: "Portfolio Summary",
    viewAssetOverview: "View your asset overview",
    recentActivity: "Recent Activity",
    checkLatestTransactions: "Check latest transactions",
    withdrawFunds: "Withdraw Funds",
    withdrawToExternal: "Withdraw to external wallet",
    walletAddresses: "Wallet Addresses",
    viewDepositAddresses: "View deposit addresses",
    transactionHistory: "Transaction History",
    viewAllTransactions: "View all transactions",
    accountSettings: "Account Settings",
    securityAndPreferences: "Security and preferences",
    yourCryptoBalances: "Your cryptocurrency balances",
    
    // Trading Interface
    orderBook: "Order Book",
    currentPrice: "Current Price",
    price: "Price",
    amount: "Amount",
    total: "Total",
    spread: "Spread",
    buyOrders: "Buy Orders",
    sellOrders: "Sell Orders",
    tradingForm: "Trading Form",
    buy: "Buy",
    sell: "Sell",
    lotSize: "Lot Size (Hands)",
    enterLots: "Enter number of lots",
    stopLossTarget: "Stop Loss Target",
    enterTarget: "Enter your target",
    startSession: "Start Session",
    stopSession: "Stop Session",
    showPL: "Show P/L",
    profitPreview: "Profit Preview",
    entryPrice: "Entry Price",
    availableBalance: "Available Balance",
    grandTotal: "Grand Total",
    
    // Login Page
    signInToAccount: "Sign in to your account",
    enterCredentials: "Enter your credentials to access your trading dashboard",
    email: "Email",
    enterEmail: "Enter your email",
    password: "Password",
    enterPassword: "Enter your password",
    signingIn: "Signing in...",
    signIn: "Sign In",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign up",
    welcomeBackToast: "Welcome back!",
    successfullySignedIn: "Successfully signed in to your trading account.",
    signInFailed: "Sign in failed",
    
    // Signup Page
    createYourAccount: "Create your account",
    joinThousands: "Join thousands of traders and start your journey",
    createPassword: "Create a password",
    confirmPassword: "Confirm Password",
    confirmYourPassword: "Confirm your password",
    creatingAccount: "Creating account...",
    alreadyHaveAccount: "Already have an account?",
    accountCreated: "Account created!",
    checkEmailConfirm: "Please check your email to confirm your account.",
    signUpFailed: "Sign up failed",
    passwordsDontMatch: "Passwords don't match",
    passwordsIdentical: "Please make sure both passwords are identical.",
    
    // Buy Crypto Page
    buyCryptocurrency: "Buy Cryptocurrency",
    priceChart24h: "Price Chart - 24H",
    realtimePriceMovements: "Real-time price movements over the last 24 hours",
    purchaseCrypto: "Purchase Crypto",
    buyWithPayment: "Buy cryptocurrency with your preferred payment method",
    selectCryptocurrency: "Select Cryptocurrency",
    amountToBuy: "Amount to Buy",
    paymentMethod: "Payment Method",
    creditDebitCard: "Credit/Debit Card",
    bankTransfer: "Bank Transfer",
    connectedWallet: "Connected Wallet",
    marketOverview: "Market Overview",
    currentCryptoPrices: "Current cryptocurrency prices",
    purchaseInitiated: "Purchase Initiated!",
    invalidAmount: "Invalid Amount",
    enterValidAmount: "Please enter a valid amount.",
    
    // Sell Crypto Page
    sellCryptocurrency: "Sell Cryptocurrency",
    yourPortfolio: "Your Portfolio",
    availableHoldings: "Available cryptocurrency holdings",
    sellCrypto: "Sell Crypto",
    convertToUsd: "Convert your cryptocurrency to USD",
    selectToSell: "Select Cryptocurrency to Sell",
    amountToSell: "Amount to Sell",
    youllReceive: "You'll receive",
    bankAccount: "Bank Account",
    paypal: "PayPal",
    debitCard: "Debit Card",
    saleCompleted: "Sale Completed!",
    saleFailed: "Sale Failed",
    failedToSell: "Failed to complete the sale. Please try again.",
    insufficientBalance: "Insufficient Balance",
    notEnoughCrypto: "You don't have enough cryptocurrency to sell.",
    minBalanceToast: "Insufficient balance. Minimum ${amount} USD required to start a session.",
    minBalanceToastDesc: "Your current {coin} balance is ${balance} USD. Please deposit to continue.",
    
    // Exchange Page
    exchangeCryptocurrency: "Exchange Cryptocurrency",
    cryptoExchange: "Crypto Exchange",
    swapBetween: "Swap between different cryptocurrencies",
    from: "From",
    to: "To",
    exchangeRate: "Exchange Rate",
    exchangeCompleted: "Exchange Completed!",
    exchangeFailed: "Exchange Failed",
    failedToExchange: "Failed to complete the exchange. Please try again.",
    notEnoughToExchange: "You don't have enough to exchange.",
    exchangeRates: "Exchange Rates",
    marketRate: "Market Rate",
    
    // Withdraw Page
    withdrawFundsTitle: "Withdraw Funds",
    chooseAndEnter: "Choose cryptocurrency and enter withdrawal details",
    selectCrypto: "Select cryptocurrency",
    withdrawalAmount: "Withdrawal Amount",
    walletAddressInput: "Wallet Address",
    networkFee: "Network Fee",
    withdrawalInitiated: "Withdrawal Initiated!",
    pendingAdminApproval: "withdrawal is pending admin approval.",
    selectCryptocurrency2: "Select Cryptocurrency",
    addressRequired: "Address Required",
    enterValidWallet: "Please enter a valid wallet address.",
    invalidWithdrawalAmount: "Invalid Amount",
    enterValidWithdrawal: "Please enter a valid withdrawal amount.",
    insufficientForWithdraw: "Insufficient Balance",
    notEnoughForWithdraw: "You don't have enough for this withdrawal.",
    
    // KYC Page
    kycVerificationTitle: "KYC Verification",
    identityVerification: "Identity Verification",
    completeIdentity: "Complete your identity verification to unlock all features",
    firstName: "First Name",
    lastName: "Last Name",
    dateOfBirth: "Date of Birth",
    phoneNumber: "Phone Number",
    address: "Address",
    documentUpload: "Document Upload",
    uploadIdentityDocs: "Upload your identity documents for verification",
    documentType: "Document Type",
    passport: "Passport",
    driversLicense: "Driver's License",
    nationalId: "National ID Card",
    frontSide: "Front Side",
    backSide: "Back Side",
    uploadFrontSide: "Upload Front Side",
    uploadBackSide: "Upload Back Side",
    optional: "Optional",
    required: "Required",
    submitDocuments: "Submit Documents for Verification",
    submittingDocuments: "Submitting Documents...",
    kycAlreadySubmitted: "KYC Already Submitted",
    kycDocumentsSubmitted: "Your KYC documents have been submitted and are under review.",
    frontDocRequired: "Front document is required for verification",
    backSideRequired: "Back side is required for",
    verificationStatus: "Verification Status",
    trackProgress: "Track your verification progress",
    emailVerification: "Email Verification",
    complete: "Complete",
    kycSubmittedSuccess: "KYC Documents Submitted Successfully!",
    kycPendingReview: "Your identity verification is now pending review. Our team will process your submission within 1-2 business days.",
    submissionFailed: "Submission Failed",
    
    // Settings Page
    settingsTitle: "Settings",
    securitySettings: "Security Settings",
    manageAccountSecurity: "Manage your account security",
    twoFactorAuth: "Two-Factor Authentication",
    addExtraLayer: "Add an extra layer of security",
    emailNotifications: "Email Notifications",
    securityAlertsEmail: "Security alerts via email",
    notificationPreferences: "Notification Preferences",
    controlNotifications: "Control what notifications you receive",
    priceAlerts: "Price Alerts",
    getNotifiedPrice: "Get notified of price changes",
    tradeConfirmations: "Trade Confirmations",
    confirmSuccessful: "Confirm successful trades",
    marketingUpdates: "Marketing Updates",
    newsAndUpdates: "News and product updates",
    savePreferences: "Save Preferences",
    accountManagement: "Account Management",
    managePasswordApi: "Manage your password and API access",
    changePassword: "Change Password",
    viewApiKeys: "View API Keys",
    passwordChangeInitiated: "Password Change Initiated!",
    checkEmailPassword: "Check your email for password reset instructions.",
    apiKeysGenerated: "API Keys Generated!",
    apiKeysReady: "Your API keys are ready for use.",
    notificationsUpdated: "Notifications Updated!",
    notificationsSaved: "Your notification preferences have been saved.",
    tradingSettingsUpdated: "Trading Settings Updated!",
    tradingPreferencesSaved: "Your trading preferences have been saved.",
    
    // VIP Offers Page
    vipTradingOffersTitle: "VIP Trading Offers",
    exclusiveOffers: "Exclusive offers for premium traders",
    
    // Transactions Page
    transactionsTitle: "Transaction History",
    allTransactions: "All Transactions",
    viewTransactions: "View your transaction history",
    date: "Date",
    type: "Type",
    status: "Status",
    pending: "Pending",
    completed: "Completed",
    failed: "Failed",
    noTransactions: "No transactions found",
    
    // Common
    loading: "Loading...",
    error: "Error",
    success: "Success",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    back: "Back",
    next: "Next",
    submit: "Submit",
    available: "available"
  },
  es: {
    // Header
    features: "Características",
    platform: "Plataforma",
    pricing: "Precios",
    supportNav: "Soporte",
    login: "Iniciar Sesión",
    getStarted: "Comenzar",
    
    // Hero
    powerYourEdge: "Potencia Tu Ventaja",
    tradeSmarter: "Opera Más Inteligente",
    winDaily: "Gana Diariamente",
    heroDescription: "Bienvenido a EdgeTrade Pro, la plataforma de trading con sede en EE.UU. creada para traders profesionales.",
    startTradingNow: "Comenzar a Operar Ahora",
    watchDemo: "Ver Demo",
    realtimeData: "Datos en Tiempo Real",
    advancedCharts: "Gráficos Avanzados",
    fastExecution: "Ejecución Rápida",
    secProtected: "Protegido por SEC",
    
    // Features Section
    builtForProfessional: "Construido para Traders Profesionales",
    featuresDescription: "Todo lo que necesitas para ejecutar tu estrategia de trading con precisión, velocidad y confianza.",
    realtimeMarketData: "Datos de Mercado en Tiempo Real",
    realtimeMarketDataDesc: "Feeds de datos ultrarrápidos con cotizaciones Level II y streaming en tiempo real para todas las principales bolsas.",
    advancedCharting: "Gráficos y Análisis Avanzados",
    advancedChartingDesc: "Gráficos de grado profesional con más de 100 indicadores técnicos, estudios personalizados y análisis multi-temporales.",
    directAccessRouting: "Enrutamiento de Acceso Directo",
    directAccessRoutingDesc: "Conéctate directamente a creadores de mercado y ECNs para la ejecución más rápida y el mejor precio disponible.",
    secRegistered: "Registrado en SEC y Protegido por SIPC",
    secRegisteredDesc: "Opera con confianza sabiendo que tu cuenta está protegida por el seguro SIPC y la regulación de la SEC.",
    subMillisecondExecution: "Ejecución Submilisegundo",
    subMillisecondExecutionDesc: "Ejecución de órdenes de latencia ultra baja con servidores colocados para máxima ventaja de velocidad.",
    competitivePricing: "Precios Competitivos",
    competitivePricingDesc: "Estructura de comisiones transparente y de bajo costo sin tarifas ocultas ni mínimos de cuenta.",
    bankLevelSecurity: "Seguridad de Nivel Bancario",
    bankLevelSecurityDesc: "Autenticación multifactor, encriptación y protección de almacenamiento en frío para tus fondos.",
    advancedOrderTypes: "Tipos de Órdenes Avanzadas",
    advancedOrderTypesDesc: "Suite completa de tipos de órdenes incluyendo órdenes bracket, stops dinámicos y estrategias algorítmicas.",
    
    // Trust Indicators
    trustedBy: "Confiado por más de 50,000 Traders Activos",
    trustDescription: "Tu seguridad y éxito son nuestras principales prioridades",
    secRegisteredTitle: "Registrado en SEC",
    secRegisteredText: "Totalmente regulado por la Comisión de Valores y Bolsa",
    sipcProtected: "Protegido por SIPC",
    sipcProtectedText: "Tus valores protegidos hasta $500,000 por el seguro SIPC",
    finraMember: "Miembro de FINRA",
    finraMemberText: "Miembro de la Autoridad Reguladora de la Industria Financiera",
    awardWinning: "Premiado",
    awardWinningText: "Mejor Plataforma de Trading 2024 - Trading Magazine",
    sslEncryption: "Encriptación SSL de 256 bits",
    tfaAuthentication: "Autenticación 2FA",
    coldStorage: "Protección de Almacenamiento en Frío",
    securityMonitoring: "Monitoreo de Seguridad 24/7",
    
    // Call to Action
    readyToDominate: "¿Listo para Dominar los Mercados?",
    ctaDescription: "Únete a miles de traders exitosos que confían en EdgeTrade Pro para sus operaciones diarias.",
    openFreeAccount: "Abrir Cuenta Gratis",
    platformDemo: "Demo de Plataforma",
    minDeposit: "Depósito mínimo de $250 requerido",
    freeRealtimeData: "Datos en tiempo real gratis para nuevas cuentas",
    customerSupport247: "Soporte al cliente 24/7",
    
    // Sidebar
    overview: "Resumen",
    exchange: "Intercambio",
    withdraw: "Retirar",
    transactions: "Transacciones",
    walletAddress: "Dirección de Cartera",
    vipTradingOffers: "Ofertas VIP de Trading",
    supportInbox: "Bandeja de Soporte",
    kycVerification: "Verificación KYC",
    settings: "Configuración",
    
    // Dashboard
    welcomeBack: "¡Bienvenido de vuelta!",
    dashboard: "Panel",
    support: "Soporte",
    myWallets: "Mis Carteras",
    trading: "Comercio",
    walletManagement: "Gestión de Cartera",
    securityVerification: "Seguridad y Verificación",
    signOut: "Cerrar Sesión",
    demoAccount: "Cuenta Demo",
    demoNotice: "Estás en modo demo con $10,000 de saldo virtual. Crea una cuenta gratis para comenzar a operar de verdad.",
    createFreeAccount: "Crear Cuenta Gratis",
    verifyKycNotice: "Por favor verifica tu información KYC antes de cualquier acción transaccional.",
    verifyNow: "Verificar Ahora",
    portfolioSummary: "Resumen del Portafolio",
    viewAssetOverview: "Ver resumen de activos",
    recentActivity: "Actividad Reciente",
    checkLatestTransactions: "Ver últimas transacciones",
    withdrawFunds: "Retirar Fondos",
    withdrawToExternal: "Retirar a cartera externa",
    walletAddresses: "Direcciones de Cartera",
    viewDepositAddresses: "Ver direcciones de depósito",
    transactionHistory: "Historial de Transacciones",
    viewAllTransactions: "Ver todas las transacciones",
    accountSettings: "Configuración de Cuenta",
    securityAndPreferences: "Seguridad y preferencias",
    yourCryptoBalances: "Tus saldos de criptomonedas",
    
    // Trading Interface
    orderBook: "Libro de Órdenes",
    currentPrice: "Precio Actual",
    price: "Precio",
    amount: "Cantidad",
    total: "Total",
    spread: "Diferencial",
    buyOrders: "Órdenes de Compra",
    sellOrders: "Órdenes de Venta",
    tradingForm: "Formulario de Trading",
    buy: "Comprar",
    sell: "Vender",
    lotSize: "Tamaño del Lote (Manos)",
    enterLots: "Ingrese número de lotes",
    stopLossTarget: "Objetivo Stop Loss",
    enterTarget: "Ingrese su objetivo",
    startSession: "Iniciar Sesión",
    stopSession: "Detener Sesión",
    showPL: "Mostrar P/L",
    profitPreview: "Vista Previa de Ganancia",
    entryPrice: "Precio de Entrada",
    availableBalance: "Saldo Disponible",
    grandTotal: "Total General",
    
    // Login Page
    signInToAccount: "Inicia sesión en tu cuenta",
    enterCredentials: "Ingresa tus credenciales para acceder a tu panel de trading",
    email: "Correo Electrónico",
    enterEmail: "Ingresa tu correo electrónico",
    password: "Contraseña",
    enterPassword: "Ingresa tu contraseña",
    signingIn: "Iniciando sesión...",
    signIn: "Iniciar Sesión",
    dontHaveAccount: "¿No tienes una cuenta?",
    signUp: "Regístrate",
    welcomeBackToast: "¡Bienvenido de vuelta!",
    successfullySignedIn: "Has iniciado sesión exitosamente en tu cuenta de trading.",
    signInFailed: "Error al iniciar sesión",
    
    // Signup Page
    createYourAccount: "Crea tu cuenta",
    joinThousands: "Únete a miles de traders y comienza tu viaje",
    createPassword: "Crea una contraseña",
    confirmPassword: "Confirmar Contraseña",
    confirmYourPassword: "Confirma tu contraseña",
    creatingAccount: "Creando cuenta...",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    accountCreated: "¡Cuenta creada!",
    checkEmailConfirm: "Por favor revisa tu correo para confirmar tu cuenta.",
    signUpFailed: "Error al registrarse",
    passwordsDontMatch: "Las contraseñas no coinciden",
    passwordsIdentical: "Por favor asegúrate de que ambas contraseñas sean idénticas.",
    
    // Buy Crypto Page
    buyCryptocurrency: "Comprar Criptomoneda",
    priceChart24h: "Gráfico de Precios - 24H",
    realtimePriceMovements: "Movimientos de precios en tiempo real de las últimas 24 horas",
    purchaseCrypto: "Comprar Cripto",
    buyWithPayment: "Compra criptomonedas con tu método de pago preferido",
    selectCryptocurrency: "Seleccionar Criptomoneda",
    amountToBuy: "Cantidad a Comprar",
    paymentMethod: "Método de Pago",
    creditDebitCard: "Tarjeta de Crédito/Débito",
    bankTransfer: "Transferencia Bancaria",
    connectedWallet: "Cartera Conectada",
    marketOverview: "Resumen del Mercado",
    currentCryptoPrices: "Precios actuales de criptomonedas",
    purchaseInitiated: "¡Compra Iniciada!",
    invalidAmount: "Cantidad Inválida",
    enterValidAmount: "Por favor ingresa una cantidad válida.",
    
    // Sell Crypto Page
    sellCryptocurrency: "Vender Criptomoneda",
    yourPortfolio: "Tu Portafolio",
    availableHoldings: "Criptomonedas disponibles",
    sellCrypto: "Vender Cripto",
    convertToUsd: "Convierte tu criptomoneda a USD",
    selectToSell: "Seleccionar Criptomoneda a Vender",
    amountToSell: "Cantidad a Vender",
    youllReceive: "Recibirás",
    bankAccount: "Cuenta Bancaria",
    paypal: "PayPal",
    debitCard: "Tarjeta de Débito",
    saleCompleted: "¡Venta Completada!",
    saleFailed: "Venta Fallida",
    failedToSell: "No se pudo completar la venta. Por favor intenta de nuevo.",
    insufficientBalance: "Saldo Insuficiente",
    notEnoughCrypto: "No tienes suficiente criptomoneda para vender.",
    minBalanceToast: "Saldo insuficiente. Se requieren ${amount} USD mínimo para iniciar una sesión.",
    minBalanceToastDesc: "Tu saldo actual de {coin} es ${balance} USD. Por favor deposita para continuar.",
    
    // Exchange Page
    exchangeCryptocurrency: "Intercambiar Criptomoneda",
    cryptoExchange: "Intercambio Cripto",
    swapBetween: "Intercambia entre diferentes criptomonedas",
    from: "Desde",
    to: "Hasta",
    exchangeRate: "Tasa de Cambio",
    exchangeCompleted: "¡Intercambio Completado!",
    exchangeFailed: "Intercambio Fallido",
    failedToExchange: "No se pudo completar el intercambio. Por favor intenta de nuevo.",
    notEnoughToExchange: "No tienes suficiente para intercambiar.",
    exchangeRates: "Tasas de Cambio",
    marketRate: "Tasa de Mercado",
    
    // Withdraw Page
    withdrawFundsTitle: "Retirar Fondos",
    chooseAndEnter: "Elige criptomoneda e ingresa detalles de retiro",
    selectCrypto: "Seleccionar criptomoneda",
    withdrawalAmount: "Cantidad de Retiro",
    walletAddressInput: "Dirección de Cartera",
    networkFee: "Tarifa de Red",
    withdrawalInitiated: "¡Retiro Iniciado!",
    pendingAdminApproval: "retiro pendiente de aprobación del administrador.",
    selectCryptocurrency2: "Seleccionar Criptomoneda",
    addressRequired: "Dirección Requerida",
    enterValidWallet: "Por favor ingresa una dirección de cartera válida.",
    invalidWithdrawalAmount: "Cantidad Inválida",
    enterValidWithdrawal: "Por favor ingresa una cantidad de retiro válida.",
    insufficientForWithdraw: "Saldo Insuficiente",
    notEnoughForWithdraw: "No tienes suficiente para este retiro.",
    
    // KYC Page
    kycVerificationTitle: "Verificación KYC",
    identityVerification: "Verificación de Identidad",
    completeIdentity: "Completa tu verificación de identidad para desbloquear todas las funciones",
    firstName: "Nombre",
    lastName: "Apellido",
    dateOfBirth: "Fecha de Nacimiento",
    phoneNumber: "Número de Teléfono",
    address: "Dirección",
    documentUpload: "Subir Documento",
    uploadIdentityDocs: "Sube tus documentos de identidad para verificación",
    documentType: "Tipo de Documento",
    passport: "Pasaporte",
    driversLicense: "Licencia de Conducir",
    nationalId: "Cédula de Identidad",
    frontSide: "Lado Frontal",
    backSide: "Lado Posterior",
    uploadFrontSide: "Subir Lado Frontal",
    uploadBackSide: "Subir Lado Posterior",
    optional: "Opcional",
    required: "Requerido",
    submitDocuments: "Enviar Documentos para Verificación",
    submittingDocuments: "Enviando Documentos...",
    kycAlreadySubmitted: "KYC Ya Enviado",
    kycDocumentsSubmitted: "Tus documentos KYC han sido enviados y están bajo revisión.",
    frontDocRequired: "El documento frontal es requerido para verificación",
    backSideRequired: "El lado posterior es requerido para",
    verificationStatus: "Estado de Verificación",
    trackProgress: "Sigue tu progreso de verificación",
    emailVerification: "Verificación de Correo",
    complete: "Completo",
    kycSubmittedSuccess: "¡Documentos KYC Enviados Exitosamente!",
    kycPendingReview: "Tu verificación de identidad está pendiente de revisión. Nuestro equipo procesará tu envío dentro de 1-2 días hábiles.",
    submissionFailed: "Envío Fallido",
    
    // Settings Page
    settingsTitle: "Configuración",
    securitySettings: "Configuración de Seguridad",
    manageAccountSecurity: "Administra la seguridad de tu cuenta",
    twoFactorAuth: "Autenticación de Dos Factores",
    addExtraLayer: "Agrega una capa extra de seguridad",
    emailNotifications: "Notificaciones por Correo",
    securityAlertsEmail: "Alertas de seguridad por correo",
    notificationPreferences: "Preferencias de Notificación",
    controlNotifications: "Controla qué notificaciones recibes",
    priceAlerts: "Alertas de Precio",
    getNotifiedPrice: "Recibe notificaciones de cambios de precio",
    tradeConfirmations: "Confirmaciones de Operaciones",
    confirmSuccessful: "Confirma operaciones exitosas",
    marketingUpdates: "Actualizaciones de Marketing",
    newsAndUpdates: "Noticias y actualizaciones de productos",
    savePreferences: "Guardar Preferencias",
    accountManagement: "Gestión de Cuenta",
    managePasswordApi: "Administra tu contraseña y acceso API",
    changePassword: "Cambiar Contraseña",
    viewApiKeys: "Ver Claves API",
    passwordChangeInitiated: "¡Cambio de Contraseña Iniciado!",
    checkEmailPassword: "Revisa tu correo para instrucciones de restablecimiento.",
    apiKeysGenerated: "¡Claves API Generadas!",
    apiKeysReady: "Tus claves API están listas para usar.",
    notificationsUpdated: "¡Notificaciones Actualizadas!",
    notificationsSaved: "Tus preferencias de notificación han sido guardadas.",
    tradingSettingsUpdated: "¡Configuración de Trading Actualizada!",
    tradingPreferencesSaved: "Tus preferencias de trading han sido guardadas.",
    
    // VIP Offers Page
    vipTradingOffersTitle: "Ofertas VIP de Trading",
    exclusiveOffers: "Ofertas exclusivas para traders premium",
    
    // Transactions Page
    transactionsTitle: "Historial de Transacciones",
    allTransactions: "Todas las Transacciones",
    viewTransactions: "Ver tu historial de transacciones",
    date: "Fecha",
    type: "Tipo",
    status: "Estado",
    pending: "Pendiente",
    completed: "Completado",
    failed: "Fallido",
    noTransactions: "No se encontraron transacciones",
    
    // Common
    loading: "Cargando...",
    error: "Error",
    success: "Éxito",
    cancel: "Cancelar",
    confirm: "Confirmar",
    save: "Guardar",
    delete: "Eliminar",
    edit: "Editar",
    close: "Cerrar",
    back: "Atrás",
    next: "Siguiente",
    submit: "Enviar",
    available: "disponible"
  },
  fr: {
    // Header
    features: "Fonctionnalités",
    platform: "Plateforme",
    pricing: "Tarifs",
    supportNav: "Support",
    login: "Se Connecter",
    getStarted: "Commencer",
    
    // Hero
    powerYourEdge: "Augmentez Votre Avantage",
    tradeSmarter: "Trader Plus Intelligemment",
    winDaily: "Gagner Quotidiennement",
    heroDescription: "Bienvenue sur EdgeTrade Pro, la plateforme de trading basée aux États-Unis conçue pour les traders sérieux.",
    startTradingNow: "Commencer à Trader Maintenant",
    watchDemo: "Voir la Démo",
    realtimeData: "Données en Temps Réel",
    advancedCharts: "Graphiques Avancés",
    fastExecution: "Exécution Rapide",
    secProtected: "Protégé par la SEC",
    
    // Features Section
    builtForProfessional: "Conçu pour les Traders Professionnels",
    featuresDescription: "Tout ce dont vous avez besoin pour exécuter votre stratégie de trading avec précision, rapidité et confiance.",
    realtimeMarketData: "Données de Marché en Temps Réel",
    realtimeMarketDataDesc: "Flux de données ultra-rapides avec cotations Level II et streaming en temps réel pour toutes les principales bourses.",
    advancedCharting: "Graphiques et Analyses Avancés",
    advancedChartingDesc: "Graphiques de qualité professionnelle avec plus de 100 indicateurs techniques, études personnalisées et analyse multi-temporelle.",
    directAccessRouting: "Routage à Accès Direct",
    directAccessRoutingDesc: "Connectez-vous directement aux teneurs de marché et ECN pour l'exécution la plus rapide et les meilleurs prix disponibles.",
    secRegistered: "Enregistré SEC et Protégé SIPC",
    secRegisteredDesc: "Tradez en toute confiance en sachant que votre compte est protégé par l'assurance SIPC et la réglementation SEC.",
    subMillisecondExecution: "Exécution Sub-milliseconde",
    subMillisecondExecutionDesc: "Exécution d'ordres à latence ultra-faible avec serveurs colocalisés pour un avantage de vitesse maximal.",
    competitivePricing: "Tarification Compétitive",
    competitivePricingDesc: "Structure de commission transparente et à faible coût sans frais cachés ni minimum de compte.",
    bankLevelSecurity: "Sécurité de Niveau Bancaire",
    bankLevelSecurityDesc: "Authentification multi-facteurs, chiffrement et protection de stockage à froid pour vos fonds.",
    advancedOrderTypes: "Types d'Ordres Avancés",
    advancedOrderTypesDesc: "Suite complète de types d'ordres incluant ordres bracket, stops suiveurs et stratégies algorithmiques.",
    
    // Trust Indicators
    trustedBy: "Approuvé par plus de 50 000 Traders Actifs",
    trustDescription: "Votre sécurité et votre succès sont nos principales priorités",
    secRegisteredTitle: "Enregistré SEC",
    secRegisteredText: "Entièrement réglementé par la Securities and Exchange Commission",
    sipcProtected: "Protégé SIPC",
    sipcProtectedText: "Vos titres protégés jusqu'à 500 000 $ par l'assurance SIPC",
    finraMember: "Membre FINRA",
    finraMemberText: "Membre de la Financial Industry Regulatory Authority",
    awardWinning: "Primé",
    awardWinningText: "Meilleure Plateforme de Trading 2024 - Trading Magazine",
    sslEncryption: "Chiffrement SSL 256 bits",
    tfaAuthentication: "Authentification 2FA",
    coldStorage: "Protection de Stockage à Froid",
    securityMonitoring: "Surveillance de Sécurité 24/7",
    
    // Call to Action
    readyToDominate: "Prêt à Dominer les Marchés ?",
    ctaDescription: "Rejoignez des milliers de traders à succès qui font confiance à EdgeTrade Pro pour leurs opérations quotidiennes.",
    openFreeAccount: "Ouvrir un Compte Gratuit",
    platformDemo: "Démo de la Plateforme",
    minDeposit: "Dépôt minimum de 250 $ requis",
    freeRealtimeData: "Données en temps réel gratuites pour les nouveaux comptes",
    customerSupport247: "Support client 24/7",
    
    // Sidebar
    overview: "Aperçu",
    exchange: "Échange",
    withdraw: "Retrait",
    transactions: "Transactions",
    walletAddress: "Adresse du Portefeuille",
    vipTradingOffers: "Offres VIP de Trading",
    supportInbox: "Boîte de Support",
    kycVerification: "Vérification KYC",
    settings: "Paramètres",
    
    // Dashboard
    welcomeBack: "Bon retour !",
    dashboard: "Tableau de bord",
    support: "Support",
    myWallets: "Mes Portefeuilles",
    trading: "Trading",
    walletManagement: "Gestion du Portefeuille",
    securityVerification: "Sécurité et Vérification",
    signOut: "Se Déconnecter",
    demoAccount: "Compte Démo",
    demoNotice: "Vous êtes en mode démo avec un solde virtuel de 10 000 $. Créez un compte gratuit pour commencer le trading réel.",
    createFreeAccount: "Créer un Compte Gratuit",
    verifyKycNotice: "Veuillez vérifier vos informations KYC avant toute action transactionnelle.",
    verifyNow: "Vérifier Maintenant",
    portfolioSummary: "Résumé du Portefeuille",
    viewAssetOverview: "Voir l'aperçu de vos actifs",
    recentActivity: "Activité Récente",
    checkLatestTransactions: "Voir les dernières transactions",
    withdrawFunds: "Retirer des Fonds",
    withdrawToExternal: "Retirer vers un portefeuille externe",
    walletAddresses: "Adresses de Portefeuille",
    viewDepositAddresses: "Voir les adresses de dépôt",
    transactionHistory: "Historique des Transactions",
    viewAllTransactions: "Voir toutes les transactions",
    accountSettings: "Paramètres du Compte",
    securityAndPreferences: "Sécurité et préférences",
    yourCryptoBalances: "Vos soldes de crypto-monnaies",
    
    // Trading Interface
    orderBook: "Carnet d'Ordres",
    currentPrice: "Prix Actuel",
    price: "Prix",
    amount: "Quantité",
    total: "Total",
    spread: "Écart",
    buyOrders: "Ordres d'Achat",
    sellOrders: "Ordres de Vente",
    tradingForm: "Formulaire de Trading",
    buy: "Acheter",
    sell: "Vendre",
    lotSize: "Taille du Lot (Mains)",
    enterLots: "Entrez le nombre de lots",
    stopLossTarget: "Objectif Stop Loss",
    enterTarget: "Entrez votre objectif",
    startSession: "Démarrer Session",
    stopSession: "Arrêter Session",
    showPL: "Afficher P/L",
    profitPreview: "Aperçu des Profits",
    entryPrice: "Prix d'Entrée",
    availableBalance: "Solde Disponible",
    grandTotal: "Total Général",
    
    // Login Page
    signInToAccount: "Connectez-vous à votre compte",
    enterCredentials: "Entrez vos identifiants pour accéder à votre tableau de bord de trading",
    email: "Email",
    enterEmail: "Entrez votre email",
    password: "Mot de passe",
    enterPassword: "Entrez votre mot de passe",
    signingIn: "Connexion...",
    signIn: "Se Connecter",
    dontHaveAccount: "Vous n'avez pas de compte ?",
    signUp: "S'inscrire",
    welcomeBackToast: "Bon retour !",
    successfullySignedIn: "Vous êtes connecté à votre compte de trading.",
    signInFailed: "Échec de la connexion",
    
    // Signup Page
    createYourAccount: "Créez votre compte",
    joinThousands: "Rejoignez des milliers de traders et commencez votre voyage",
    createPassword: "Créez un mot de passe",
    confirmPassword: "Confirmer le Mot de passe",
    confirmYourPassword: "Confirmez votre mot de passe",
    creatingAccount: "Création du compte...",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    accountCreated: "Compte créé !",
    checkEmailConfirm: "Veuillez vérifier votre email pour confirmer votre compte.",
    signUpFailed: "Échec de l'inscription",
    passwordsDontMatch: "Les mots de passe ne correspondent pas",
    passwordsIdentical: "Veuillez vous assurer que les deux mots de passe sont identiques.",
    
    // Buy Crypto Page
    buyCryptocurrency: "Acheter des Crypto-monnaies",
    priceChart24h: "Graphique des Prix - 24H",
    realtimePriceMovements: "Mouvements de prix en temps réel des dernières 24 heures",
    purchaseCrypto: "Acheter Crypto",
    buyWithPayment: "Achetez des crypto-monnaies avec votre méthode de paiement préférée",
    selectCryptocurrency: "Sélectionner Crypto-monnaie",
    amountToBuy: "Montant à Acheter",
    paymentMethod: "Méthode de Paiement",
    creditDebitCard: "Carte de Crédit/Débit",
    bankTransfer: "Virement Bancaire",
    connectedWallet: "Portefeuille Connecté",
    marketOverview: "Aperçu du Marché",
    currentCryptoPrices: "Prix actuels des crypto-monnaies",
    purchaseInitiated: "Achat Initié !",
    invalidAmount: "Montant Invalide",
    enterValidAmount: "Veuillez entrer un montant valide.",
    
    // Sell Crypto Page
    sellCryptocurrency: "Vendre des Crypto-monnaies",
    yourPortfolio: "Votre Portefeuille",
    availableHoldings: "Crypto-monnaies disponibles",
    sellCrypto: "Vendre Crypto",
    convertToUsd: "Convertissez votre crypto-monnaie en USD",
    selectToSell: "Sélectionner Crypto-monnaie à Vendre",
    amountToSell: "Montant à Vendre",
    youllReceive: "Vous recevrez",
    bankAccount: "Compte Bancaire",
    paypal: "PayPal",
    debitCard: "Carte de Débit",
    saleCompleted: "Vente Complétée !",
    saleFailed: "Vente Échouée",
    failedToSell: "Impossible de compléter la vente. Veuillez réessayer.",
    insufficientBalance: "Solde Insuffisant",
    notEnoughCrypto: "Vous n'avez pas assez de crypto-monnaie à vendre.",
    minBalanceToast: "Solde insuffisant. Minimum ${amount} USD requis pour démarrer une session.",
    minBalanceToastDesc: "Votre solde {coin} actuel est de ${balance} USD. Veuillez déposer pour continuer.",
    
    // Exchange Page
    exchangeCryptocurrency: "Échanger des Crypto-monnaies",
    cryptoExchange: "Échange Crypto",
    swapBetween: "Échangez entre différentes crypto-monnaies",
    from: "De",
    to: "Vers",
    exchangeRate: "Taux de Change",
    exchangeCompleted: "Échange Complété !",
    exchangeFailed: "Échange Échoué",
    failedToExchange: "Impossible de compléter l'échange. Veuillez réessayer.",
    notEnoughToExchange: "Vous n'avez pas assez pour échanger.",
    exchangeRates: "Taux de Change",
    marketRate: "Taux du Marché",
    
    // Withdraw Page
    withdrawFundsTitle: "Retirer des Fonds",
    chooseAndEnter: "Choisissez la crypto-monnaie et entrez les détails du retrait",
    selectCrypto: "Sélectionner crypto-monnaie",
    withdrawalAmount: "Montant du Retrait",
    walletAddressInput: "Adresse du Portefeuille",
    networkFee: "Frais de Réseau",
    withdrawalInitiated: "Retrait Initié !",
    pendingAdminApproval: "retrait en attente d'approbation administrative.",
    selectCryptocurrency2: "Sélectionner Crypto-monnaie",
    addressRequired: "Adresse Requise",
    enterValidWallet: "Veuillez entrer une adresse de portefeuille valide.",
    invalidWithdrawalAmount: "Montant Invalide",
    enterValidWithdrawal: "Veuillez entrer un montant de retrait valide.",
    insufficientForWithdraw: "Solde Insuffisant",
    notEnoughForWithdraw: "Vous n'avez pas assez pour ce retrait.",
    
    // KYC Page
    kycVerificationTitle: "Vérification KYC",
    identityVerification: "Vérification d'Identité",
    completeIdentity: "Complétez votre vérification d'identité pour débloquer toutes les fonctionnalités",
    firstName: "Prénom",
    lastName: "Nom",
    dateOfBirth: "Date de Naissance",
    phoneNumber: "Numéro de Téléphone",
    address: "Adresse",
    documentUpload: "Téléchargement de Document",
    uploadIdentityDocs: "Téléchargez vos documents d'identité pour vérification",
    documentType: "Type de Document",
    passport: "Passeport",
    driversLicense: "Permis de Conduire",
    nationalId: "Carte d'Identité Nationale",
    frontSide: "Recto",
    backSide: "Verso",
    uploadFrontSide: "Télécharger le Recto",
    uploadBackSide: "Télécharger le Verso",
    optional: "Optionnel",
    required: "Requis",
    submitDocuments: "Soumettre les Documents pour Vérification",
    submittingDocuments: "Soumission des Documents...",
    kycAlreadySubmitted: "KYC Déjà Soumis",
    kycDocumentsSubmitted: "Vos documents KYC ont été soumis et sont en cours de révision.",
    frontDocRequired: "Le document recto est requis pour la vérification",
    backSideRequired: "Le verso est requis pour",
    verificationStatus: "Statut de Vérification",
    trackProgress: "Suivez votre progression de vérification",
    emailVerification: "Vérification Email",
    complete: "Complète",
    kycSubmittedSuccess: "Documents KYC Soumis avec Succès !",
    kycPendingReview: "Votre vérification d'identité est en attente de révision. Notre équipe traitera votre soumission dans 1-2 jours ouvrables.",
    submissionFailed: "Soumission Échouée",
    
    // Settings Page
    settingsTitle: "Paramètres",
    securitySettings: "Paramètres de Sécurité",
    manageAccountSecurity: "Gérez la sécurité de votre compte",
    twoFactorAuth: "Authentification à Deux Facteurs",
    addExtraLayer: "Ajoutez une couche de sécurité supplémentaire",
    emailNotifications: "Notifications par Email",
    securityAlertsEmail: "Alertes de sécurité par email",
    notificationPreferences: "Préférences de Notification",
    controlNotifications: "Contrôlez les notifications que vous recevez",
    priceAlerts: "Alertes de Prix",
    getNotifiedPrice: "Soyez notifié des changements de prix",
    tradeConfirmations: "Confirmations de Trades",
    confirmSuccessful: "Confirmez les trades réussis",
    marketingUpdates: "Mises à Jour Marketing",
    newsAndUpdates: "Actualités et mises à jour produit",
    savePreferences: "Enregistrer les Préférences",
    accountManagement: "Gestion du Compte",
    managePasswordApi: "Gérez votre mot de passe et accès API",
    changePassword: "Changer le Mot de Passe",
    viewApiKeys: "Voir les Clés API",
    passwordChangeInitiated: "Changement de Mot de Passe Initié !",
    checkEmailPassword: "Vérifiez votre email pour les instructions de réinitialisation.",
    apiKeysGenerated: "Clés API Générées !",
    apiKeysReady: "Vos clés API sont prêtes à l'utilisation.",
    notificationsUpdated: "Notifications Mises à Jour !",
    notificationsSaved: "Vos préférences de notification ont été enregistrées.",
    tradingSettingsUpdated: "Paramètres de Trading Mis à Jour !",
    tradingPreferencesSaved: "Vos préférences de trading ont été enregistrées.",
    
    // VIP Offers Page
    vipTradingOffersTitle: "Offres VIP de Trading",
    exclusiveOffers: "Offres exclusives pour les traders premium",
    
    // Transactions Page
    transactionsTitle: "Historique des Transactions",
    allTransactions: "Toutes les Transactions",
    viewTransactions: "Voir votre historique de transactions",
    date: "Date",
    type: "Type",
    status: "Statut",
    pending: "En Attente",
    completed: "Complété",
    failed: "Échoué",
    noTransactions: "Aucune transaction trouvée",
    
    // Common
    loading: "Chargement...",
    error: "Erreur",
    success: "Succès",
    cancel: "Annuler",
    confirm: "Confirmer",
    save: "Enregistrer",
    delete: "Supprimer",
    edit: "Modifier",
    close: "Fermer",
    back: "Retour",
    next: "Suivant",
    submit: "Soumettre",
    available: "disponible"
  },
  de: {
    // Header
    features: "Funktionen",
    platform: "Plattform",
    pricing: "Preise",
    supportNav: "Support",
    login: "Anmelden",
    getStarted: "Loslegen",
    
    // Hero
    powerYourEdge: "Stärken Sie Ihren Vorteil",
    tradeSmarter: "Intelligenter Handeln",
    winDaily: "Täglich Gewinnen",
    heroDescription: "Willkommen bei EdgeTrade Pro, der in den USA ansässigen Handelsplattform für ernsthafte Daytrader.",
    startTradingNow: "Jetzt Handeln",
    watchDemo: "Demo Ansehen",
    realtimeData: "Echtzeit-Daten",
    advancedCharts: "Erweiterte Charts",
    fastExecution: "Schnelle Ausführung",
    secProtected: "SEC-Geschützt",
    
    // Features Section
    builtForProfessional: "Für Professionelle Händler Entwickelt",
    featuresDescription: "Alles, was Sie brauchen, um Ihre Handelsstrategie mit Präzision, Geschwindigkeit und Vertrauen auszuführen.",
    realtimeMarketData: "Echtzeit-Marktdaten",
    realtimeMarketDataDesc: "Blitzschnelle Daten-Feeds mit Level-II-Kursen und Echtzeit-Streaming für alle großen Börsen.",
    advancedCharting: "Erweiterte Charts & Analysen",
    advancedChartingDesc: "Professionelle Charts mit über 100 technischen Indikatoren, benutzerdefinierten Studien und Multi-Zeitrahmen-Analyse.",
    directAccessRouting: "Direktes Zugangs-Routing",
    directAccessRoutingDesc: "Verbinden Sie sich direkt mit Market Makern und ECNs für die schnellste Ausführung und beste Preisstellung.",
    secRegistered: "SEC-Registriert & SIPC-Geschützt",
    secRegisteredDesc: "Handeln Sie mit Vertrauen, da Ihr Konto durch SIPC-Versicherung und SEC-Regulierung geschützt ist.",
    subMillisecondExecution: "Sub-Millisekunden-Ausführung",
    subMillisecondExecutionDesc: "Ultra-niedrige Latenz-Order-Ausführung mit co-lokalisierten Servern für maximalen Geschwindigkeitsvorteil.",
    competitivePricing: "Wettbewerbsfähige Preise",
    competitivePricingDesc: "Transparente, kostengünstige Provisionsstruktur ohne versteckte Gebühren oder Kontomindestbeträge.",
    bankLevelSecurity: "Sicherheit auf Bankniveau",
    bankLevelSecurityDesc: "Multi-Faktor-Authentifizierung, Verschlüsselung und Cold-Storage-Schutz für Ihre Gelder.",
    advancedOrderTypes: "Erweiterte Ordertypen",
    advancedOrderTypesDesc: "Vollständige Suite von Ordertypen einschließlich Bracket-Orders, Trailing-Stops und algorithmischen Strategien.",
    
    // Trust Indicators
    trustedBy: "Vertraut von über 50.000 Aktiven Händlern",
    trustDescription: "Ihre Sicherheit und Ihr Erfolg sind unsere obersten Prioritäten",
    secRegisteredTitle: "SEC-Registriert",
    secRegisteredText: "Vollständig reguliert durch die Securities and Exchange Commission",
    sipcProtected: "SIPC-Geschützt",
    sipcProtectedText: "Ihre Wertpapiere bis zu 500.000 $ durch SIPC-Versicherung geschützt",
    finraMember: "FINRA-Mitglied",
    finraMemberText: "Mitglied der Financial Industry Regulatory Authority",
    awardWinning: "Preisgekrönt",
    awardWinningText: "Beste Handelsplattform 2024 - Trading Magazine",
    sslEncryption: "256-Bit-SSL-Verschlüsselung",
    tfaAuthentication: "2FA-Authentifizierung",
    coldStorage: "Cold-Storage-Schutz",
    securityMonitoring: "24/7-Sicherheitsüberwachung",
    
    // Call to Action
    readyToDominate: "Bereit, die Märkte zu Dominieren?",
    ctaDescription: "Schließen Sie sich Tausenden erfolgreicher Daytrader an, die EdgeTrade Pro für ihre täglichen Handelsoperationen vertrauen.",
    openFreeAccount: "Kostenloses Konto Eröffnen",
    platformDemo: "Plattform-Demo",
    minDeposit: "Mindesteinzahlung von 250 $ erforderlich",
    freeRealtimeData: "Kostenlose Echtzeit-Daten für neue Konten",
    customerSupport247: "24/7-Kundensupport",
    
    // Sidebar
    overview: "Übersicht",
    exchange: "Austausch",
    withdraw: "Abheben",
    transactions: "Transaktionen",
    walletAddress: "Wallet-Adresse",
    vipTradingOffers: "VIP-Handelsangebote",
    supportInbox: "Support-Posteingang",
    kycVerification: "KYC-Verifizierung",
    settings: "Einstellungen",
    
    // Dashboard
    welcomeBack: "Willkommen zurück!",
    dashboard: "Dashboard",
    support: "Support",
    myWallets: "Meine Wallets",
    trading: "Handel",
    walletManagement: "Wallet-Verwaltung",
    securityVerification: "Sicherheit & Verifizierung",
    signOut: "Abmelden",
    demoAccount: "Demo-Konto",
    demoNotice: "Sie sind im Demo-Modus mit 10.000 $ virtuellem Guthaben. Erstellen Sie ein kostenloses Konto, um mit echtem Handel zu beginnen.",
    createFreeAccount: "Kostenloses Konto Erstellen",
    verifyKycNotice: "Bitte verifizieren Sie Ihre KYC-Informationen vor jeder Transaktion.",
    verifyNow: "Jetzt Verifizieren",
    portfolioSummary: "Portfolio-Übersicht",
    viewAssetOverview: "Vermögensübersicht anzeigen",
    recentActivity: "Neueste Aktivität",
    checkLatestTransactions: "Neueste Transaktionen prüfen",
    withdrawFunds: "Geld Abheben",
    withdrawToExternal: "An externe Wallet abheben",
    walletAddresses: "Wallet-Adressen",
    viewDepositAddresses: "Einzahlungsadressen anzeigen",
    transactionHistory: "Transaktionshistorie",
    viewAllTransactions: "Alle Transaktionen anzeigen",
    accountSettings: "Kontoeinstellungen",
    securityAndPreferences: "Sicherheit und Präferenzen",
    yourCryptoBalances: "Ihre Kryptowährungsguthaben",
    
    // Trading Interface
    orderBook: "Orderbuch",
    currentPrice: "Aktueller Preis",
    price: "Preis",
    amount: "Menge",
    total: "Gesamt",
    spread: "Spread",
    buyOrders: "Kaufaufträge",
    sellOrders: "Verkaufsaufträge",
    tradingForm: "Trading-Formular",
    buy: "Kaufen",
    sell: "Verkaufen",
    lotSize: "Losgröße (Hände)",
    enterLots: "Anzahl der Lots eingeben",
    stopLossTarget: "Stop-Loss-Ziel",
    enterTarget: "Ihr Ziel eingeben",
    startSession: "Sitzung Starten",
    stopSession: "Sitzung Beenden",
    showPL: "P/L Anzeigen",
    profitPreview: "Gewinn-Vorschau",
    entryPrice: "Einstiegspreis",
    availableBalance: "Verfügbares Guthaben",
    grandTotal: "Gesamtsumme",
    
    // Login Page
    signInToAccount: "In Ihr Konto einloggen",
    enterCredentials: "Geben Sie Ihre Anmeldedaten ein, um auf Ihr Trading-Dashboard zuzugreifen",
    email: "E-Mail",
    enterEmail: "E-Mail eingeben",
    password: "Passwort",
    enterPassword: "Passwort eingeben",
    signingIn: "Anmeldung...",
    signIn: "Anmelden",
    dontHaveAccount: "Haben Sie kein Konto?",
    signUp: "Registrieren",
    welcomeBackToast: "Willkommen zurück!",
    successfullySignedIn: "Erfolgreich in Ihr Trading-Konto eingeloggt.",
    signInFailed: "Anmeldung fehlgeschlagen",
    
    // Signup Page
    createYourAccount: "Erstellen Sie Ihr Konto",
    joinThousands: "Schließen Sie sich Tausenden von Händlern an und beginnen Sie Ihre Reise",
    createPassword: "Passwort erstellen",
    confirmPassword: "Passwort Bestätigen",
    confirmYourPassword: "Bestätigen Sie Ihr Passwort",
    creatingAccount: "Konto wird erstellt...",
    alreadyHaveAccount: "Haben Sie bereits ein Konto?",
    accountCreated: "Konto erstellt!",
    checkEmailConfirm: "Bitte überprüfen Sie Ihre E-Mail, um Ihr Konto zu bestätigen.",
    signUpFailed: "Registrierung fehlgeschlagen",
    passwordsDontMatch: "Passwörter stimmen nicht überein",
    passwordsIdentical: "Bitte stellen Sie sicher, dass beide Passwörter identisch sind.",
    
    // Buy Crypto Page
    buyCryptocurrency: "Kryptowährung Kaufen",
    priceChart24h: "Preisdiagramm - 24H",
    realtimePriceMovements: "Echtzeit-Preisbewegungen der letzten 24 Stunden",
    purchaseCrypto: "Krypto Kaufen",
    buyWithPayment: "Kaufen Sie Kryptowährung mit Ihrer bevorzugten Zahlungsmethode",
    selectCryptocurrency: "Kryptowährung Auswählen",
    amountToBuy: "Kaufbetrag",
    paymentMethod: "Zahlungsmethode",
    creditDebitCard: "Kredit-/Debitkarte",
    bankTransfer: "Banküberweisung",
    connectedWallet: "Verbundene Wallet",
    marketOverview: "Marktübersicht",
    currentCryptoPrices: "Aktuelle Kryptowährungspreise",
    purchaseInitiated: "Kauf Eingeleitet!",
    invalidAmount: "Ungültiger Betrag",
    enterValidAmount: "Bitte geben Sie einen gültigen Betrag ein.",
    
    // Sell Crypto Page
    sellCryptocurrency: "Kryptowährung Verkaufen",
    yourPortfolio: "Ihr Portfolio",
    availableHoldings: "Verfügbare Kryptowährungsbestände",
    sellCrypto: "Krypto Verkaufen",
    convertToUsd: "Konvertieren Sie Ihre Kryptowährung in USD",
    selectToSell: "Kryptowährung zum Verkaufen Auswählen",
    amountToSell: "Verkaufsbetrag",
    youllReceive: "Sie erhalten",
    bankAccount: "Bankkonto",
    paypal: "PayPal",
    debitCard: "Debitkarte",
    saleCompleted: "Verkauf Abgeschlossen!",
    saleFailed: "Verkauf Fehlgeschlagen",
    failedToSell: "Verkauf konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.",
    insufficientBalance: "Unzureichendes Guthaben",
    notEnoughCrypto: "Sie haben nicht genug Kryptowährung zum Verkaufen.",
    minBalanceToast: "Unzureichendes Guthaben. Mindestens ${amount} USD erforderlich, um eine Sitzung zu starten.",
    minBalanceToastDesc: "Ihr aktuelles {coin}-Guthaben beträgt ${balance} USD. Bitte zahlen Sie ein, um fortzufahren.",
    
    // Exchange Page
    exchangeCryptocurrency: "Kryptowährung Tauschen",
    cryptoExchange: "Krypto-Austausch",
    swapBetween: "Tauschen Sie zwischen verschiedenen Kryptowährungen",
    from: "Von",
    to: "Nach",
    exchangeRate: "Wechselkurs",
    exchangeCompleted: "Austausch Abgeschlossen!",
    exchangeFailed: "Austausch Fehlgeschlagen",
    failedToExchange: "Austausch konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.",
    notEnoughToExchange: "Sie haben nicht genug zum Tauschen.",
    exchangeRates: "Wechselkurse",
    marketRate: "Marktkurs",
    
    // Withdraw Page
    withdrawFundsTitle: "Geld Abheben",
    chooseAndEnter: "Wählen Sie Kryptowährung und geben Sie Abhebungsdetails ein",
    selectCrypto: "Kryptowährung auswählen",
    withdrawalAmount: "Abhebungsbetrag",
    walletAddressInput: "Wallet-Adresse",
    networkFee: "Netzwerkgebühr",
    withdrawalInitiated: "Abhebung Eingeleitet!",
    pendingAdminApproval: "Abhebung wartet auf Admin-Genehmigung.",
    selectCryptocurrency2: "Kryptowährung Auswählen",
    addressRequired: "Adresse Erforderlich",
    enterValidWallet: "Bitte geben Sie eine gültige Wallet-Adresse ein.",
    invalidWithdrawalAmount: "Ungültiger Betrag",
    enterValidWithdrawal: "Bitte geben Sie einen gültigen Abhebungsbetrag ein.",
    insufficientForWithdraw: "Unzureichendes Guthaben",
    notEnoughForWithdraw: "Sie haben nicht genug für diese Abhebung.",
    
    // KYC Page
    kycVerificationTitle: "KYC-Verifizierung",
    identityVerification: "Identitätsverifizierung",
    completeIdentity: "Schließen Sie Ihre Identitätsverifizierung ab, um alle Funktionen freizuschalten",
    firstName: "Vorname",
    lastName: "Nachname",
    dateOfBirth: "Geburtsdatum",
    phoneNumber: "Telefonnummer",
    address: "Adresse",
    documentUpload: "Dokument-Upload",
    uploadIdentityDocs: "Laden Sie Ihre Ausweisdokumente zur Verifizierung hoch",
    documentType: "Dokumententyp",
    passport: "Reisepass",
    driversLicense: "Führerschein",
    nationalId: "Personalausweis",
    frontSide: "Vorderseite",
    backSide: "Rückseite",
    uploadFrontSide: "Vorderseite Hochladen",
    uploadBackSide: "Rückseite Hochladen",
    optional: "Optional",
    required: "Erforderlich",
    submitDocuments: "Dokumente zur Verifizierung Einreichen",
    submittingDocuments: "Dokumente werden eingereicht...",
    kycAlreadySubmitted: "KYC Bereits Eingereicht",
    kycDocumentsSubmitted: "Ihre KYC-Dokumente wurden eingereicht und werden überprüft.",
    frontDocRequired: "Vorderseitendokument ist für die Verifizierung erforderlich",
    backSideRequired: "Rückseite ist erforderlich für",
    verificationStatus: "Verifizierungsstatus",
    trackProgress: "Verfolgen Sie Ihren Verifizierungsfortschritt",
    emailVerification: "E-Mail-Verifizierung",
    complete: "Abgeschlossen",
    kycSubmittedSuccess: "KYC-Dokumente Erfolgreich Eingereicht!",
    kycPendingReview: "Ihre Identitätsverifizierung wartet auf Überprüfung. Unser Team wird Ihre Einreichung innerhalb von 1-2 Werktagen bearbeiten.",
    submissionFailed: "Einreichung Fehlgeschlagen",
    
    // Settings Page
    settingsTitle: "Einstellungen",
    securitySettings: "Sicherheitseinstellungen",
    manageAccountSecurity: "Verwalten Sie Ihre Kontosicherheit",
    twoFactorAuth: "Zwei-Faktor-Authentifizierung",
    addExtraLayer: "Fügen Sie eine zusätzliche Sicherheitsebene hinzu",
    emailNotifications: "E-Mail-Benachrichtigungen",
    securityAlertsEmail: "Sicherheitswarnungen per E-Mail",
    notificationPreferences: "Benachrichtigungseinstellungen",
    controlNotifications: "Kontrollieren Sie, welche Benachrichtigungen Sie erhalten",
    priceAlerts: "Preiswarnungen",
    getNotifiedPrice: "Benachrichtigungen bei Preisänderungen erhalten",
    tradeConfirmations: "Handelsbestätigungen",
    confirmSuccessful: "Erfolgreiche Trades bestätigen",
    marketingUpdates: "Marketing-Updates",
    newsAndUpdates: "Nachrichten und Produkt-Updates",
    savePreferences: "Einstellungen Speichern",
    accountManagement: "Kontoverwaltung",
    managePasswordApi: "Verwalten Sie Ihr Passwort und API-Zugang",
    changePassword: "Passwort Ändern",
    viewApiKeys: "API-Schlüssel Anzeigen",
    passwordChangeInitiated: "Passwortänderung Eingeleitet!",
    checkEmailPassword: "Überprüfen Sie Ihre E-Mail für Anweisungen zum Zurücksetzen.",
    apiKeysGenerated: "API-Schlüssel Generiert!",
    apiKeysReady: "Ihre API-Schlüssel sind einsatzbereit.",
    notificationsUpdated: "Benachrichtigungen Aktualisiert!",
    notificationsSaved: "Ihre Benachrichtigungseinstellungen wurden gespeichert.",
    tradingSettingsUpdated: "Handelseinstellungen Aktualisiert!",
    tradingPreferencesSaved: "Ihre Handelseinstellungen wurden gespeichert.",
    
    // VIP Offers Page
    vipTradingOffersTitle: "VIP-Handelsangebote",
    exclusiveOffers: "Exklusive Angebote für Premium-Händler",
    
    // Transactions Page
    transactionsTitle: "Transaktionshistorie",
    allTransactions: "Alle Transaktionen",
    viewTransactions: "Ihre Transaktionshistorie anzeigen",
    date: "Datum",
    type: "Typ",
    status: "Status",
    pending: "Ausstehend",
    completed: "Abgeschlossen",
    failed: "Fehlgeschlagen",
    noTransactions: "Keine Transaktionen gefunden",
    
    // Common
    loading: "Wird geladen...",
    error: "Fehler",
    success: "Erfolg",
    cancel: "Abbrechen",
    confirm: "Bestätigen",
    save: "Speichern",
    delete: "Löschen",
    edit: "Bearbeiten",
    close: "Schließen",
    back: "Zurück",
    next: "Weiter",
    submit: "Absenden",
    available: "verfügbar"
  },
  zh: {
    // Header
    features: "功能",
    platform: "平台",
    pricing: "价格",
    supportNav: "支持",
    login: "登录",
    getStarted: "开始使用",
    
    // Hero
    powerYourEdge: "增强您的优势",
    tradeSmarter: "更智能交易",
    winDaily: "每日获胜",
    heroDescription: "欢迎来到EdgeTrade Pro，专为认真的日间交易者打造的美国交易平台。",
    startTradingNow: "立即开始交易",
    watchDemo: "观看演示",
    realtimeData: "实时数据",
    advancedCharts: "高级图表",
    fastExecution: "快速执行",
    secProtected: "SEC保护",
    
    // Features Section
    builtForProfessional: "为专业交易者打造",
    featuresDescription: "您需要的一切，以精确、快速和自信地执行您的交易策略。",
    realtimeMarketData: "实时市场数据",
    realtimeMarketDataDesc: "闪电般快速的数据源，具有Level II报价和所有主要交易所的实时流媒体。",
    advancedCharting: "高级图表与分析",
    advancedChartingDesc: "专业级图表，具有100多个技术指标、自定义研究和多时间框架分析。",
    directAccessRouting: "直接访问路由",
    directAccessRoutingDesc: "直接连接做市商和ECN，以获得最快的执行速度和最佳定价。",
    secRegistered: "SEC注册和SIPC保护",
    secRegisteredDesc: "放心交易，知道您的账户受到SIPC保险和SEC监管的保护。",
    subMillisecondExecution: "亚毫秒执行",
    subMillisecondExecutionDesc: "超低延迟订单执行，配备协同定位服务器以获得最大速度优势。",
    competitivePricing: "有竞争力的定价",
    competitivePricingDesc: "透明、低成本的佣金结构，无隐藏费用或账户最低要求。",
    bankLevelSecurity: "银行级安全",
    bankLevelSecurityDesc: "多因素认证、加密和冷存储保护您的资金。",
    advancedOrderTypes: "高级订单类型",
    advancedOrderTypesDesc: "完整的订单类型套件，包括括号订单、跟踪止损和算法策略。",
    
    // Trust Indicators
    trustedBy: "受到50,000多名活跃交易者的信任",
    trustDescription: "您的安全和成功是我们的首要任务",
    secRegisteredTitle: "SEC注册",
    secRegisteredText: "完全受证券交易委员会监管",
    sipcProtected: "SIPC保护",
    sipcProtectedText: "您的证券受SIPC保险保护，最高达$500,000",
    finraMember: "FINRA成员",
    finraMemberText: "金融业监管局成员",
    awardWinning: "获奖平台",
    awardWinningText: "2024年最佳交易平台 - Trading Magazine",
    sslEncryption: "256位SSL加密",
    tfaAuthentication: "2FA认证",
    coldStorage: "冷存储保护",
    securityMonitoring: "24/7安全监控",
    
    // Call to Action
    readyToDominate: "准备好主导市场了吗？",
    ctaDescription: "加入数千名成功的日间交易者，他们信任EdgeTrade Pro进行日常交易操作。",
    openFreeAccount: "开设免费账户",
    platformDemo: "平台演示",
    minDeposit: "需要$250最低存款",
    freeRealtimeData: "新账户免费实时数据",
    customerSupport247: "24/7客户支持",
    
    // Sidebar
    overview: "概览",
    exchange: "交换",
    withdraw: "提取",
    transactions: "交易记录",
    walletAddress: "钱包地址",
    vipTradingOffers: "VIP交易优惠",
    supportInbox: "支持收件箱",
    kycVerification: "KYC验证",
    settings: "设置",
    
    // Dashboard
    welcomeBack: "欢迎回来！",
    dashboard: "仪表板",
    support: "支持",
    myWallets: "我的钱包",
    trading: "交易",
    walletManagement: "钱包管理",
    securityVerification: "安全与验证",
    signOut: "登出",
    demoAccount: "演示账户",
    demoNotice: "您处于演示模式，拥有$10,000虚拟余额。创建免费账户开始真实交易。",
    createFreeAccount: "创建免费账户",
    verifyKycNotice: "请在进行任何交易操作前验证您的KYC信息。",
    verifyNow: "立即验证",
    portfolioSummary: "投资组合摘要",
    viewAssetOverview: "查看资产概览",
    recentActivity: "最近活动",
    checkLatestTransactions: "查看最新交易",
    withdrawFunds: "提取资金",
    withdrawToExternal: "提取到外部钱包",
    walletAddresses: "钱包地址",
    viewDepositAddresses: "查看存款地址",
    transactionHistory: "交易历史",
    viewAllTransactions: "查看所有交易",
    accountSettings: "账户设置",
    securityAndPreferences: "安全和偏好设置",
    yourCryptoBalances: "您的加密货币余额",
    
    // Trading Interface
    orderBook: "订单簿",
    currentPrice: "当前价格",
    price: "价格",
    amount: "数量",
    total: "总计",
    spread: "价差",
    buyOrders: "买单",
    sellOrders: "卖单",
    tradingForm: "交易表单",
    buy: "买入",
    sell: "卖出",
    lotSize: "手数",
    enterLots: "输入手数",
    stopLossTarget: "止损目标",
    enterTarget: "输入目标",
    startSession: "开始会话",
    stopSession: "停止会话",
    showPL: "显示盈亏",
    profitPreview: "利润预览",
    entryPrice: "入场价格",
    availableBalance: "可用余额",
    grandTotal: "总计",
    
    // Login Page
    signInToAccount: "登录您的账户",
    enterCredentials: "输入您的凭据以访问交易仪表板",
    email: "电子邮件",
    enterEmail: "输入您的电子邮件",
    password: "密码",
    enterPassword: "输入您的密码",
    signingIn: "登录中...",
    signIn: "登录",
    dontHaveAccount: "没有账户？",
    signUp: "注册",
    welcomeBackToast: "欢迎回来！",
    successfullySignedIn: "成功登录您的交易账户。",
    signInFailed: "登录失败",
    
    // Signup Page
    createYourAccount: "创建您的账户",
    joinThousands: "加入数千名交易者，开始您的旅程",
    createPassword: "创建密码",
    confirmPassword: "确认密码",
    confirmYourPassword: "确认您的密码",
    creatingAccount: "创建账户中...",
    alreadyHaveAccount: "已有账户？",
    accountCreated: "账户已创建！",
    checkEmailConfirm: "请检查您的电子邮件以确认您的账户。",
    signUpFailed: "注册失败",
    passwordsDontMatch: "密码不匹配",
    passwordsIdentical: "请确保两个密码相同。",
    
    // Buy Crypto Page
    buyCryptocurrency: "购买加密货币",
    priceChart24h: "价格图表 - 24小时",
    realtimePriceMovements: "过去24小时的实时价格走势",
    purchaseCrypto: "购买加密货币",
    buyWithPayment: "使用您喜欢的支付方式购买加密货币",
    selectCryptocurrency: "选择加密货币",
    amountToBuy: "购买金额",
    paymentMethod: "支付方式",
    creditDebitCard: "信用卡/借记卡",
    bankTransfer: "银行转账",
    connectedWallet: "已连接钱包",
    marketOverview: "市场概览",
    currentCryptoPrices: "当前加密货币价格",
    purchaseInitiated: "购买已启动！",
    invalidAmount: "无效金额",
    enterValidAmount: "请输入有效金额。",
    
    // Sell Crypto Page
    sellCryptocurrency: "出售加密货币",
    yourPortfolio: "您的投资组合",
    availableHoldings: "可用加密货币持仓",
    sellCrypto: "出售加密货币",
    convertToUsd: "将您的加密货币转换为美元",
    selectToSell: "选择要出售的加密货币",
    amountToSell: "出售金额",
    youllReceive: "您将收到",
    bankAccount: "银行账户",
    paypal: "PayPal",
    debitCard: "借记卡",
    saleCompleted: "出售完成！",
    saleFailed: "出售失败",
    failedToSell: "无法完成出售。请重试。",
    insufficientBalance: "余额不足",
    notEnoughCrypto: "您没有足够的加密货币可以出售。",
    minBalanceToast: "余额不足。开始会话至少需要 ${amount} 美元。",
    minBalanceToastDesc: "您当前的 {coin} 余额为 ${balance} 美元。请充值以继续。",
    
    // Exchange Page
    exchangeCryptocurrency: "交换加密货币",
    cryptoExchange: "加密货币交换",
    swapBetween: "在不同加密货币之间交换",
    from: "从",
    to: "到",
    exchangeRate: "汇率",
    exchangeCompleted: "交换完成！",
    exchangeFailed: "交换失败",
    failedToExchange: "无法完成交换。请重试。",
    notEnoughToExchange: "您没有足够的余额进行交换。",
    exchangeRates: "汇率",
    marketRate: "市场汇率",
    
    // Withdraw Page
    withdrawFundsTitle: "提取资金",
    chooseAndEnter: "选择加密货币并输入提取详情",
    selectCrypto: "选择加密货币",
    withdrawalAmount: "提取金额",
    walletAddressInput: "钱包地址",
    networkFee: "网络费用",
    withdrawalInitiated: "提取已启动！",
    pendingAdminApproval: "提取正在等待管理员批准。",
    selectCryptocurrency2: "选择加密货币",
    addressRequired: "需要地址",
    enterValidWallet: "请输入有效的钱包地址。",
    invalidWithdrawalAmount: "无效金额",
    enterValidWithdrawal: "请输入有效的提取金额。",
    insufficientForWithdraw: "余额不足",
    notEnoughForWithdraw: "您没有足够的余额进行此次提取。",
    
    // KYC Page
    kycVerificationTitle: "KYC验证",
    identityVerification: "身份验证",
    completeIdentity: "完成身份验证以解锁所有功能",
    firstName: "名",
    lastName: "姓",
    dateOfBirth: "出生日期",
    phoneNumber: "电话号码",
    address: "地址",
    documentUpload: "上传文件",
    uploadIdentityDocs: "上传您的身份文件进行验证",
    documentType: "文件类型",
    passport: "护照",
    driversLicense: "驾驶证",
    nationalId: "身份证",
    frontSide: "正面",
    backSide: "背面",
    uploadFrontSide: "上传正面",
    uploadBackSide: "上传背面",
    optional: "可选",
    required: "必需",
    submitDocuments: "提交文件进行验证",
    submittingDocuments: "提交文件中...",
    kycAlreadySubmitted: "KYC已提交",
    kycDocumentsSubmitted: "您的KYC文件已提交，正在审核中。",
    frontDocRequired: "正面文件是验证所必需的",
    backSideRequired: "背面是必需的",
    verificationStatus: "验证状态",
    trackProgress: "跟踪您的验证进度",
    emailVerification: "电子邮件验证",
    complete: "完成",
    kycSubmittedSuccess: "KYC文件提交成功！",
    kycPendingReview: "您的身份验证正在等待审核。我们的团队将在1-2个工作日内处理您的提交。",
    submissionFailed: "提交失败",
    
    // Settings Page
    settingsTitle: "设置",
    securitySettings: "安全设置",
    manageAccountSecurity: "管理您的账户安全",
    twoFactorAuth: "双因素认证",
    addExtraLayer: "添加额外的安全层",
    emailNotifications: "电子邮件通知",
    securityAlertsEmail: "通过电子邮件接收安全警报",
    notificationPreferences: "通知偏好设置",
    controlNotifications: "控制您接收的通知",
    priceAlerts: "价格警报",
    getNotifiedPrice: "价格变动时获取通知",
    tradeConfirmations: "交易确认",
    confirmSuccessful: "确认成功的交易",
    marketingUpdates: "营销更新",
    newsAndUpdates: "新闻和产品更新",
    savePreferences: "保存偏好设置",
    accountManagement: "账户管理",
    managePasswordApi: "管理您的密码和API访问",
    changePassword: "更改密码",
    viewApiKeys: "查看API密钥",
    passwordChangeInitiated: "密码更改已启动！",
    checkEmailPassword: "请检查您的电子邮件获取重置说明。",
    apiKeysGenerated: "API密钥已生成！",
    apiKeysReady: "您的API密钥已准备就绪。",
    notificationsUpdated: "通知已更新！",
    notificationsSaved: "您的通知偏好设置已保存。",
    tradingSettingsUpdated: "交易设置已更新！",
    tradingPreferencesSaved: "您的交易偏好设置已保存。",
    
    // VIP Offers Page
    vipTradingOffersTitle: "VIP交易优惠",
    exclusiveOffers: "高级交易者的专属优惠",
    
    // Transactions Page
    transactionsTitle: "交易历史",
    allTransactions: "所有交易",
    viewTransactions: "查看您的交易历史",
    date: "日期",
    type: "类型",
    status: "状态",
    pending: "待处理",
    completed: "已完成",
    failed: "失败",
    noTransactions: "未找到交易",
    
    // Common
    loading: "加载中...",
    error: "错误",
    success: "成功",
    cancel: "取消",
    confirm: "确认",
    save: "保存",
    delete: "删除",
    edit: "编辑",
    close: "关闭",
    back: "返回",
    next: "下一步",
    submit: "提交",
    available: "可用"
  },
  sk: {
    // Header
    features: "Funkcie",
    platform: "Platforma",
    pricing: "Cenník",
    supportNav: "Podpora",
    login: "Prihlásiť sa",
    getStarted: "Začať",
    
    // Hero
    powerYourEdge: "Posilnite svoju výhodu",
    tradeSmarter: "Obchodujte múdrejšie",
    winDaily: "Zarábajte denne",
    heroDescription: "Vitajte na EdgeTrade Pro, obchodnej platforme so sídlom v USA vytvorenej pre serióznych denných obchodníkov.",
    startTradingNow: "Začať obchodovať",
    watchDemo: "Pozrieť demo",
    realtimeData: "Dáta v reálnom čase",
    advancedCharts: "Pokročilé grafy",
    fastExecution: "Rýchle vykonávanie",
    secProtected: "Chránené SEC",
    
    // Features Section
    builtForProfessional: "Vytvorené pre profesionálnych obchodníkov",
    featuresDescription: "Všetko, čo potrebujete na realizáciu vašej obchodnej stratégie s presnosťou, rýchlosťou a dôverou.",
    realtimeMarketData: "Trhové dáta v reálnom čase",
    realtimeMarketDataDesc: "Bleskovo rýchle dátové kanály s kotáciami Level II a streamovaním v reálnom čase pre všetky hlavné burzy.",
    advancedCharting: "Pokročilé grafy a analytika",
    advancedChartingDesc: "Profesionálne grafy s viac ako 100 technickými indikátormi, vlastnými štúdiami a multi-časovou analýzou.",
    directAccessRouting: "Priame smerovanie prístupu",
    directAccessRoutingDesc: "Pripojte sa priamo k tvorcom trhu a ECN pre najrýchlejšie vykonávanie a najlepšie dostupné ceny.",
    secRegistered: "Registrované SEC a chránené SIPC",
    secRegisteredDesc: "Obchodujte s dôverou, vediac, že váš účet je chránený poistením SIPC a reguláciou SEC.",
    subMillisecondExecution: "Sub-milisekundové vykonávanie",
    subMillisecondExecutionDesc: "Ultra nízka latencia vykonávania príkazov s kolokovanými servermi pre maximálnu rýchlostnú výhodu.",
    competitivePricing: "Konkurenčné ceny",
    competitivePricingDesc: "Transparentná, nízkonákladová štruktúra provízií bez skrytých poplatkov alebo minimálnych účtov.",
    bankLevelSecurity: "Bezpečnosť na úrovni banky",
    bankLevelSecurityDesc: "Viacfaktorová autentifikácia, šifrovanie a ochrana studeného úložiska pre vaše prostriedky.",
    advancedOrderTypes: "Pokročilé typy príkazov",
    advancedOrderTypesDesc: "Kompletná sada typov príkazov vrátane bracket príkazov, trailing stopov a algoritmických stratégií.",
    
    // Trust Indicators
    trustedBy: "Dôveruje nám viac ako 50 000 aktívnych obchodníkov",
    trustDescription: "Vaša bezpečnosť a úspech sú našimi hlavnými prioritami",
    secRegisteredTitle: "Registrované SEC",
    secRegisteredText: "Plne regulované Komisiou pre cenné papiere a burzy",
    sipcProtected: "Chránené SIPC",
    sipcProtectedText: "Vaše cenné papiere chránené do $500 000 poistením SIPC",
    finraMember: "Člen FINRA",
    finraMemberText: "Člen Úradu pre reguláciu finančného priemyslu",
    awardWinning: "Ocenená platforma",
    awardWinningText: "Najlepšia obchodná platforma 2024 - Trading Magazine",
    sslEncryption: "256-bitové SSL šifrovanie",
    tfaAuthentication: "2FA autentifikácia",
    coldStorage: "Ochrana studeného úložiska",
    securityMonitoring: "24/7 bezpečnostný monitoring",
    
    // Call to Action
    readyToDominate: "Pripravení ovládnuť trhy?",
    ctaDescription: "Pripojte sa k tisícom úspešných denných obchodníkov, ktorí dôverujú EdgeTrade Pro pre svoje denné obchodné operácie.",
    openFreeAccount: "Otvoriť bezplatný účet",
    platformDemo: "Demo platformy",
    minDeposit: "Vyžadovaný minimálny vklad $250",
    freeRealtimeData: "Bezplatné dáta v reálnom čase pre nové účty",
    customerSupport247: "24/7 zákaznícka podpora",
    
    // Sidebar
    overview: "Prehľad",
    exchange: "Výmena",
    withdraw: "Výber",
    transactions: "Transakcie",
    walletAddress: "Adresa peňaženky",
    vipTradingOffers: "VIP obchodné ponuky",
    supportInbox: "Schránka podpory",
    kycVerification: "KYC overenie",
    settings: "Nastavenia",
    
    // Dashboard
    welcomeBack: "Vitajte späť!",
    dashboard: "Prehľad",
    support: "Podpora",
    myWallets: "Moje peňaženky",
    trading: "Obchodovanie",
    walletManagement: "Správa peňaženky",
    securityVerification: "Bezpečnosť a overenie",
    signOut: "Odhlásiť sa",
    demoAccount: "Demo účet",
    demoNotice: "Ste v demo režime s virtuálnym zostatkom $10 000. Vytvorte si bezplatný účet a začnite skutočne obchodovať.",
    createFreeAccount: "Vytvoriť bezplatný účet",
    verifyKycNotice: "Pred akoukoľvek transakciou si prosím overte KYC informácie.",
    verifyNow: "Overiť teraz",
    portfolioSummary: "Súhrn portfólia",
    viewAssetOverview: "Zobraziť prehľad aktív",
    recentActivity: "Posledná aktivita",
    checkLatestTransactions: "Skontrolovať posledné transakcie",
    withdrawFunds: "Vybrať prostriedky",
    withdrawToExternal: "Výber na externú peňaženku",
    walletAddresses: "Adresy peňaženiek",
    viewDepositAddresses: "Zobraziť adresy na vklad",
    transactionHistory: "História transakcií",
    viewAllTransactions: "Zobraziť všetky transakcie",
    accountSettings: "Nastavenia účtu",
    securityAndPreferences: "Bezpečnosť a preferencie",
    yourCryptoBalances: "Vaše kryptomenové zostatky",
    
    // Trading Interface
    orderBook: "Kniha príkazov",
    currentPrice: "Aktuálna cena",
    price: "Cena",
    amount: "Suma",
    total: "Celkom",
    spread: "Rozpätie",
    buyOrders: "Nákupné príkazy",
    sellOrders: "Predajné príkazy",
    tradingForm: "Obchodný formulár",
    buy: "Kúpiť",
    sell: "Predať",
    lotSize: "Veľkosť lotu (Ruky)",
    enterLots: "Zadajte počet lotov",
    stopLossTarget: "Cieľ Stop Loss",
    enterTarget: "Zadajte svoj cieľ",
    startSession: "Začať reláciu",
    stopSession: "Ukončiť reláciu",
    showPL: "Zobraziť Z/S",
    profitPreview: "Náhľad zisku",
    entryPrice: "Vstupná cena",
    availableBalance: "Dostupný zostatok",
    grandTotal: "Celková suma",
    
    // Login Page
    signInToAccount: "Prihláste sa do svojho účtu",
    enterCredentials: "Zadajte svoje prihlasovacie údaje pre prístup k obchodnému panelu",
    email: "E-mail",
    enterEmail: "Zadajte e-mail",
    password: "Heslo",
    enterPassword: "Zadajte heslo",
    signingIn: "Prihlasovanie...",
    signIn: "Prihlásiť sa",
    dontHaveAccount: "Nemáte účet?",
    signUp: "Zaregistrovať sa",
    welcomeBackToast: "Vitajte späť!",
    successfullySignedIn: "Úspešne ste sa prihlásili do obchodného účtu.",
    signInFailed: "Prihlásenie zlyhalo",
    
    // Signup Page
    createYourAccount: "Vytvorte si účet",
    joinThousands: "Pripojte sa k tisícom obchodníkov a začnite svoju cestu",
    createPassword: "Vytvorte heslo",
    confirmPassword: "Potvrďte heslo",
    confirmYourPassword: "Potvrďte svoje heslo",
    creatingAccount: "Vytváranie účtu...",
    alreadyHaveAccount: "Už máte účet?",
    accountCreated: "Účet vytvorený!",
    checkEmailConfirm: "Skontrolujte si e-mail a potvrďte svoj účet.",
    signUpFailed: "Registrácia zlyhala",
    passwordsDontMatch: "Heslá sa nezhodujú",
    passwordsIdentical: "Uistite sa, že obe heslá sú rovnaké.",
    
    // Buy Crypto Page
    buyCryptocurrency: "Kúpiť kryptomenu",
    priceChart24h: "Cenový graf - 24H",
    realtimePriceMovements: "Pohyby cien v reálnom čase za posledných 24 hodín",
    purchaseCrypto: "Nákup kryptomeny",
    buyWithPayment: "Kúpte kryptomenu preferovanou platobnou metódou",
    selectCryptocurrency: "Vyberte kryptomenu",
    amountToBuy: "Suma na nákup",
    paymentMethod: "Platobná metóda",
    creditDebitCard: "Kreditná/Debetná karta",
    bankTransfer: "Bankový prevod",
    connectedWallet: "Pripojená peňaženka",
    marketOverview: "Prehľad trhu",
    currentCryptoPrices: "Aktuálne ceny kryptomien",
    purchaseInitiated: "Nákup iniciovaný!",
    invalidAmount: "Neplatná suma",
    enterValidAmount: "Zadajte platnú sumu.",
    
    // Sell Crypto Page
    sellCryptocurrency: "Predať kryptomenu",
    yourPortfolio: "Vaše portfólio",
    availableHoldings: "Dostupné kryptomenové držby",
    sellCrypto: "Predať kryptomenu",
    convertToUsd: "Preveďte svoju kryptomenu na USD",
    selectToSell: "Vyberte kryptomenu na predaj",
    amountToSell: "Suma na predaj",
    youllReceive: "Dostanete",
    bankAccount: "Bankový účet",
    paypal: "PayPal",
    debitCard: "Debetná karta",
    saleCompleted: "Predaj dokončený!",
    saleFailed: "Predaj zlyhal",
    failedToSell: "Nepodarilo sa dokončiť predaj. Skúste to znova.",
    insufficientBalance: "Nedostatočný zostatok",
    notEnoughCrypto: "Nemáte dostatok kryptomeny na predaj.",
    minBalanceToast: "Nedostatočný zostatok. Na spustenie relácie je potrebných minimálne ${amount} USD.",
    minBalanceToastDesc: "Váš aktuálny zostatok {coin} je ${balance} USD. Pre pokračovanie prosím vložte prostriedky.",
    
    // Exchange Page
    exchangeCryptocurrency: "Výmena kryptomeny",
    cryptoExchange: "Krypto výmena",
    swapBetween: "Vymieňajte medzi rôznymi kryptomenami",
    from: "Z",
    to: "Na",
    exchangeRate: "Výmenný kurz",
    exchangeCompleted: "Výmena dokončená!",
    exchangeFailed: "Výmena zlyhala",
    failedToExchange: "Nepodarilo sa dokončiť výmenu. Skúste to znova.",
    notEnoughToExchange: "Nemáte dostatok na výmenu.",
    exchangeRates: "Výmenné kurzy",
    marketRate: "Trhový kurz",
    
    // Withdraw Page
    withdrawFundsTitle: "Výber prostriedkov",
    chooseAndEnter: "Vyberte kryptomenu a zadajte údaje o výbere",
    selectCrypto: "Vyberte kryptomenu",
    withdrawalAmount: "Suma výberu",
    walletAddressInput: "Adresa peňaženky",
    networkFee: "Sieťový poplatok",
    withdrawalInitiated: "Výber iniciovaný!",
    pendingAdminApproval: "výber čaká na schválenie administrátorom.",
    selectCryptocurrency2: "Vyberte kryptomenu",
    addressRequired: "Adresa je povinná",
    enterValidWallet: "Zadajte platnú adresu peňaženky.",
    invalidWithdrawalAmount: "Neplatná suma",
    enterValidWithdrawal: "Zadajte platnú sumu výberu.",
    insufficientForWithdraw: "Nedostatočný zostatok",
    notEnoughForWithdraw: "Nemáte dostatok prostriedkov na tento výber.",
    
    // KYC Page
    kycVerificationTitle: "KYC overenie",
    identityVerification: "Overenie totožnosti",
    completeIdentity: "Dokončite overenie totožnosti pre odomknutie všetkých funkcií",
    firstName: "Meno",
    lastName: "Priezvisko",
    dateOfBirth: "Dátum narodenia",
    phoneNumber: "Telefónne číslo",
    address: "Adresa",
    documentUpload: "Nahranie dokumentu",
    uploadIdentityDocs: "Nahrajte svoje doklady totožnosti na overenie",
    documentType: "Typ dokumentu",
    passport: "Pas",
    driversLicense: "Vodičský preukaz",
    nationalId: "Občiansky preukaz",
    frontSide: "Predná strana",
    backSide: "Zadná strana",
    uploadFrontSide: "Nahrať prednú stranu",
    uploadBackSide: "Nahrať zadnú stranu",
    optional: "Voliteľné",
    required: "Povinné",
    submitDocuments: "Odoslať dokumenty na overenie",
    submittingDocuments: "Odosielanie dokumentov...",
    kycAlreadySubmitted: "KYC už bolo odoslané",
    kycDocumentsSubmitted: "Vaše KYC dokumenty boli odoslané a sú v procese kontroly.",
    frontDocRequired: "Predný dokument je povinný na overenie",
    backSideRequired: "Zadná strana je povinná pre",
    verificationStatus: "Stav overenia",
    trackProgress: "Sledujte priebeh overenia",
    emailVerification: "Overenie e-mailu",
    complete: "Dokončené",
    kycSubmittedSuccess: "KYC dokumenty úspešne odoslané!",
    kycPendingReview: "Vaše overenie totožnosti čaká na kontrolu. Náš tím spracuje vašu žiadosť do 1-2 pracovných dní.",
    submissionFailed: "Odoslanie zlyhalo",
    
    // Settings Page
    settingsTitle: "Nastavenia",
    securitySettings: "Nastavenia bezpečnosti",
    manageAccountSecurity: "Spravujte bezpečnosť svojho účtu",
    twoFactorAuth: "Dvojfaktorová autentifikácia",
    addExtraLayer: "Pridajte ďalšiu vrstvu bezpečnosti",
    emailNotifications: "E-mailové upozornenia",
    securityAlertsEmail: "Bezpečnostné upozornenia e-mailom",
    notificationPreferences: "Preferencie upozornení",
    controlNotifications: "Ovládajte, aké upozornenia dostávate",
    priceAlerts: "Cenové upozornenia",
    getNotifiedPrice: "Dostávajte upozornenia na zmeny cien",
    tradeConfirmations: "Potvrdenia obchodov",
    confirmSuccessful: "Potvrďte úspešné obchody",
    marketingUpdates: "Marketingové aktualizácie",
    newsAndUpdates: "Novinky a aktualizácie produktov",
    savePreferences: "Uložiť preferencie",
    accountManagement: "Správa účtu",
    managePasswordApi: "Spravujte svoje heslo a API prístup",
    changePassword: "Zmeniť heslo",
    viewApiKeys: "Zobraziť API kľúče",
    passwordChangeInitiated: "Zmena hesla iniciovaná!",
    checkEmailPassword: "Skontrolujte e-mail s pokynmi na obnovenie hesla.",
    apiKeysGenerated: "API kľúče vygenerované!",
    apiKeysReady: "Vaše API kľúče sú pripravené na použitie.",
    notificationsUpdated: "Upozornenia aktualizované!",
    notificationsSaved: "Vaše preferencie upozornení boli uložené.",
    tradingSettingsUpdated: "Obchodné nastavenia aktualizované!",
    tradingPreferencesSaved: "Vaše obchodné preferencie boli uložené.",
    
    // VIP Offers Page
    vipTradingOffersTitle: "VIP obchodné ponuky",
    exclusiveOffers: "Exkluzívne ponuky pre prémiových obchodníkov",
    
    // Transactions Page
    transactionsTitle: "História transakcií",
    allTransactions: "Všetky transakcie",
    viewTransactions: "Zobraziť históriu transakcií",
    date: "Dátum",
    type: "Typ",
    status: "Stav",
    pending: "Čakajúce",
    completed: "Dokončené",
    failed: "Zlyhané",
    noTransactions: "Žiadne transakcie",
    
    // Common
    loading: "Načítavanie...",
    error: "Chyba",
    success: "Úspech",
    cancel: "Zrušiť",
    confirm: "Potvrdiť",
    save: "Uložiť",
    delete: "Odstrániť",
    edit: "Upraviť",
    close: "Zavrieť",
    back: "Späť",
    next: "Ďalej",
    submit: "Odoslať",
    available: "dostupné"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState('en');

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const t = (key: string, language: string) => {
  return translations[language as keyof typeof translations]?.[key] || key;
};
